### ISSUE TITLE
Migration script for older versions

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluFormBundle#12]
The https://github.com/alexander-schranz/sulu-form-bundle 1.0 release should be migrate able to 0.1 of this repo.

## TODO

Table Names:

 - [x] `l91_fo_dynamic` -> `fo_dynamics`
 - [x] `l91_fo_form` -> `fo_forms`
 - [x] `l91_fo_form_translations` -> `l91_fo_form_translations`
 - [x] `l91_fo_form_fields` -> `fo_form_fields`
 - [x] `l91_fo_form_field_translations` -> `fo_form_field_translations`

```sql
RENAME TABLE `l91_fo_dynamic` TO `fo_dynamics`;
RENAME TABLE `l91_fo_form` TO `fo_forms`;
RENAME TABLE `l91_fo_form_field_translations` TO `fo_form_field_translations`;
RENAME TABLE `l91_fo_form_fields` TO `fo_form_fields`;
RENAME TABLE `l91_fo_form_translations` TO `fo_form_translations`;
```

Other changes:

 - [x] CSRF Token include

**Comment by alexander-schranz** [comment]
@trickreich is the SQL list complete or is something missing for the migration?

**Comment by alexander-schranz** [comment]
Fixed in https://github.com/alexander-schranz/sulu-form-bundle
