### ISSUE TITLE
Upgrade Roadmap to Sulu 2.0 compatibility

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluFormBundle#190]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Bundle Version | for 2.0
| Sulu Version | for 2.0
| Browser Version | Browser name and version

## Changes

- [x] **1. Implement new List of Forms** (implemented in #190)

Remove fieldsAction and create list xml for forms.

- [x] **2. Implement form for forms** (implemented in #190)

Create form without fields section. 

- [x] **3. Extend FormMetadataProvider (Sulu Core changes needed)** (implemented in #192)

~~EvaluateFormItemExpressions should be an own service?
MetadataProviderRegistry should handle Providers as chain so an own Provider can be implemented to add the FormMetaData for the Fields blocks.~~

Extend sulu to have multiple form meta data loaders and create a custom one in the form bundle to load the form_details form.

- [x] **4. Dynamic List Fields implementation for Data Tab (Sulu Core changes needed)** (implemented in #197)

We need a option in the RouteBuilder which does made it possible to add parameters to the metadata request. So the ListMetaProvider chain get this options and can dynamically add FieldDescriptors. 

Use addRouterAttributesToListMetadata ... ['id' => 'id']
Use addRouterAttributesToListStore to add a filter for this list. 

- [x] **5. Page Tab** (#211) 

Register a new route for Pages and set the tabCondition dynamically over loadedStructureMetadata to add the tab only for this structures which has the single_form_selection content type.

Use addRouterAttributesToListStore to add a filter for this list. 

- [x] **6. Database**

Currently there is a strange mix about data when having a look at Dynamic.orm.xml

https://github.com/sulu/SuluFormBundle/blob/1.0.0-RC7/Resources/config/doctrine/Dynamic.orm.xml

The entity should be reduced to some basic fields:

 - id: int
 - (uuid: string)
 - type (maybe resourceKey): string
 - typeId (maybe resourceId): string
 - locale: ?string (5)
 - webspaceKey: ?string (64)
 - typeName (maybe resourceName / resourceTitle): ?string (128)
 - data: array
 - auditableFields
 - form: relation to form

For this all other fields need to be migrated into data field json, fields should only be set in data when the column have data for it.

This will also fix the MySQL 8 Incompatibility see https://github.com/sulu/SuluFormBundle/pull/199

- [x] **7. Dynamic.php** #255 

The magic function and the geter and setters should be removed and should not longer exist:

https://github.com/sulu/SuluFormBundle/blob/1.0.0-RC7/Entity/Dynamic.php#L244-L287

- [x] **8. Controller Dependency Injection** #252

Controller need to be changed to dependency injection.

- [x] **9. Event Dispatcher Update** #253

https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching

- [x] **10. Mailchimp List Select** #198

- [x] **11. Add .editorconfig file**

- [x] **12. Configure php-cs-fixer**

- [x] **13. Install and configure phpstan**

- [x] **14. Use yaml as format for route configuration**

**Comment by alexander-schranz** [comment]
1. and 2. will be the first steps which will be implemented by @markusmoosbrugger
if this is working he can then continue with 3. and then 4.

**Comment by kleinkoerkamp** [comment]
@alexander-schranz in which step is the 'Data' tab implemented. The tab where you can see the results and export it?

**Comment by alexander-schranz** [comment]
@kleinkoerkamp thats part of 4. (did update the title) and need some changes in the sulu/sulu before this can be implemented. @markusmoosbrugger will work on 3. currently which will be similiar to 4. because in both cases we need to have the MetadataRegistry of sulu/sulu be able to get its data from multiple providers per type and key.
