### ISSUE TITLE
Rename the composer/packagist name to sulu/form-bundle

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluFormBundle#223]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Bundle Version | for 2.0
| Sulu Version | -
| Browser Version | -

#### Actual Behavior

The current composer/packagist is `sulu/sulu-form-bundle` when we moved it from my namespace to sulu core the sulu- prefix was not removed.

#### Expected Behavior

We don't use the sulu- prefix somewhere else so it would maybe be better to use `sulu/form-bundle` the 2.0 release would maybe be good to rename the package.

https://github.com/composer/packagist/issues/47 We can Abandoned the old package we will just lose the download statistics on packagist.

@sulu/core-team what do you think 👍 / 👎 

#### TODO

 - [x] rename in composer.json
 - [x] publish with new name
 - [x] abandoned old name and link to new package
 - [x] rename **crowdin** project

**Comment by danrot** [comment]
Totally in for that, but if we do it, we also have to update the name of the project on crowdin.

**Comment by alexander-schranz** [comment]
@danrot good point added a todo list.

**Comment by alexander-schranz** [comment]
@danrot can you rename the crowdin package?

**Comment by danrot** [comment]
done!

**Comment by alexander-schranz** [comment]
Thank you!
