### ISSUE TITLE
Refractoring Bundle structure and form process

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluFormBundle#8]
Here I describe the whole refractoring which is needed before the first release to avoid future bc breaks:

# Structure

 - Admin
   - FormAdmin.php
   - FormNavigationProvider.php
   - DynamicListNavigationProvider.php `( new )`
   - StaticListNavigationProvider.php `( rename )`
 - Content
   - Types
      - FormSelect.php
 - Controller
   - FormController.php
   - FormWebsiteController.php
   - StaticController.php `( renamed )`
   - DynamicController.php `( new )`
 - DependencyInjection
   - CompilerPass
     - StaticListProviderCompilerPass.php `( rename )`
     - DynamicListBuilderCompilerPass.php `( new )`
     - DynamicFormFieldTypeCompilerPass.php `( new )`
   - Configuration.php
   - SuluFormExtension.php
 - Dynamic
   - FormBuilder.php `( new )`
   - FormBuilderInterface.php `( new )`
   - FormFieldTypePool.php `( new )`
   - FormFieldTypeInterface.php `( new )`
   - Types
     - ...
 - Entity
   - Dynamic.php
   - Form.php
   - FormEmail.php `( new )`
   - FormEmailTranslation.php `( new )`
   - FormField.php
   - FormFieldTranslation.php
   - FormRepository.php `( moved )`
   - FormTranslation.php
 - Event
   - Listener
      - RequestListener.php `( moved )`
   - Subscriber
      - MailSubscriber.php `( new )`
      - MailchimpListSubscriber.php `( moved )`
      - FormSubmitSubscriber `( new )`
   - FormValidateEvent.php `( new )`
   - FormSubmitEvent.php `( new )`
   - FormSavedEvent.php `( renamed )`
 - Form
   - Type
     - AbstractType.php `( remove )`
     - DynamicFormType `( refractor )`
     - SuluMediaType `( new )`
   - FormHandler.php `( refractor )`
   - FormLoader.php `( new )`
 - ListBuilder
   - DynamicListBuilder.php `( new )`
   - DynamicListBuilderInterface.php `( new )`
   - DynamicListFactory.php `( new )`
   - DynamicListFactoryInterface.php `( new )`
   - StaticListBuilder.php `( renamed (moved provider) )`
   - StaticListFactory.php `( renamed (moved provider) )`
 - Mail
   - SwiftMailerHelper.php `( renamed )`
   - NullMailerHelper.php `( renamed )`
   - MailerHelperInterface.php `( renamed )`
 - Manager
   - FormManager.php
 - Media
   - CollectionStrategyInterface.php
   - CollectionTreeStrategy.php `( new default )`
   - CollectionSingleStrategy.php
 - Resources
     - ...

# FormBuilder

Main part is the Form builder what is needed to create a dynamic form.

 - [x] Form ID
 - [x] Type
 - [x] TypeId
 - [x] TypeName
 - [x] Locale (optional)
 - [x] Name (optional default "form") (needed when have multiple forms)

# Dynamic Entity

 - [x] uuid -> typeId
 - [x] new `type` (default is "page") 
 - [x] new `typeName` (default is structure title) 

# Sketch

![img_20161126_151337](https://cloud.githubusercontent.com/assets/1698337/20960569/5e6c7cee-bc61-11e6-83b4-7a9c0e61e230.jpg)

# TODOs 

Exist issues and PRs:

 - [x] #4 Dynamic Form Field Pool
 - [x] #17 Include Mail Subscriber
 - [x] #24 Split form from Structure

**Comment by alexander-schranz** [comment]
@wachterjohannes maybe you can add your thoughts about the new structure.

**Comment by alexander-schranz** [comment]
@wachterjohannes should we call the `DynamicListNavigationProvider` -> `DynamicListContentNavigationProvider` as it is only the navigation provider to add a tab to content templates?

**Comment by alexander-schranz** [comment]
fixed by the Symfony 3 restructuring #83
